Revert to using x-www-form-urlencoded to submit requests, instead of json.
Passing through a stringified JSON object causes Safari to trip up with the following error
when ZAF tries to _addAuthenticityToken to the payload:

TypeError: Attempted to assign to readonly property